apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::448704481726:role/eksctl-eksctl-demo-nodegroup-ng-e-NodeInstanceRole-80XT1DV5TQE5
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::448704481726:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-05T10:43:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1593"
  uid: 6a1dc584-1c03-4dc9-a1ca-eff990cd1d06
